/**
 * Minimal task set that the globalSetup creates via the real API when the
 * test account has fewer than 5 tasks. Shaped to match what the backend
 * expects in the POST /tasks body.
 */

export const SEED_TASKS = [
  {
    title: { en: "Finish homepage wireframes for client review", zh: "完成客户评审用的首页线框" },
    desc: { en: "Hero, features section, footer.", zh: "Hero、功能区、Footer。" },
    quadrant: "Q1",
    today: true,
    due: "today",
    duration: 90,
    pomos_total: 4,
    assignee_ids: [],
    conviction: 0.92,
    next_step: { en: "Open Hero frame · Outline 3 layout options", zh: "打开 Hero 画板 · 列 3 个版式" },
    reason: {
      en: "Due today and blocks the next design stage.",
      zh: "今天截止,会卡住下一阶段。",
    },
    not_now: [],
    ai_suggest: null,
  },
  {
    title: { en: "Draft Q3 OKRs", zh: "起草 Q3 OKR 初稿" },
    quadrant: "Q2",
    today: true,
    due: "Fri",
    duration: 60,
    pomos_total: 3,
    assignee_ids: [],
    conviction: null,
    next_step: null,
    reason: null,
    not_now: [],
    ai_suggest: null,
  },
  {
    title: { en: "Reply to investor follow-up email", zh: "回复投资人跟进邮件" },
    quadrant: "Q1",
    today: true,
    due: "today",
    duration: 20,
    pomos_total: 1,
    assignee_ids: [],
    conviction: null,
    next_step: null,
    reason: null,
    not_now: [],
    ai_suggest: null,
  },
  {
    title: { en: "Approve Acme invoices", zh: "审批 Acme 发票" },
    quadrant: "Q3",
    today: true,
    due: "today",
    duration: 15,
    pomos_total: 1,
    assignee_ids: [],
    conviction: null,
    next_step: null,
    reason: null,
    not_now: [],
    ai_suggest: null,
  },
  {
    title: { en: "Clean up Downloads folder", zh: "清理下载文件夹" },
    quadrant: "Q4",
    today: false,
    due: null,
    duration: 15,
    pomos_total: 1,
    assignee_ids: [],
    conviction: null,
    next_step: null,
    reason: null,
    not_now: [],
    ai_suggest: null,
  },
  {
    title: { en: "Plan team offsite agenda", zh: "策划团队 offsite 议程" },
    quadrant: "unclassified",
    today: false,
    due: null,
    duration: 45,
    pomos_total: 2,
    assignee_ids: [],
    conviction: null,
    next_step: null,
    reason: null,
    not_now: [],
    ai_suggest: "Q2",
  },
];
